// Builds inc/icons.php (inline SVG helper) from the lucide icons the React app used.
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const root = path.resolve(import.meta.dirname, '../..');
const dir = path.join(root, 'node_modules/lucide-react/dist/esm/icons');
const names = { Phone:'phone', Mail:'mail', Search:'search', User:'user', Heart:'heart', ShoppingBag:'shopping-bag', ShoppingCart:'shopping-cart', Menu:'menu', ChevronDown:'chevron-down', ChevronRight:'chevron-right', ChevronLeft:'chevron-left', X:'x', Home:'house', Grid:'grid-3x3', Truck:'truck', ShieldCheck:'shield-check', Headphones:'headphones', RotateCcw:'rotate-ccw', Star:'star', Plus:'plus', Minus:'minus', Trash2:'trash-2', ArrowLeft:'arrow-left', ArrowRight:'arrow-right', SlidersHorizontal:'sliders-horizontal', MapPin:'map-pin', Banknote:'banknote', Check:'check', Droplets:'droplets', Sparkles:'sparkles', Leaf:'leaf', FlaskConical:'flask-conical', Timer:'timer', Lock:'lock', BadgeCheck:'badge-check', CheckCircle:'circle-check-big', CreditCard:'credit-card', MapPinned:'map-pinned', LogOut:'log-out', LayoutDashboard:'layout-dashboard', Package:'package', Download:'download', Receipt:'receipt', KeyRound:'key-round' };

let out = "<?php\n/** Inline Lucide icons (generated by tools/generate-icons.mjs). */\nif ( ! defined( 'ABSPATH' ) ) { exit; }\n\nfunction skino_icon_paths() {\n\treturn array(\n";
for (const [k, file] of Object.entries(names)) {
  const src = fs.readFileSync(path.join(dir, `${file}.mjs`), 'utf8');
  const m = /const __iconNode = (\[[\s\S]*?\]);\s*\n\s*const /.exec(src);
  if (!m) { console.error('missing', k); continue; }
  const nodes = eval(m[1]);
  const svg = nodes.map(([tag, attrs]) => {
    const a = Object.entries(attrs).filter(([n]) => n !== 'key').map(([n, v]) => `${n}="${v}"`).join(' ');
    return `<${tag} ${a}/>`;
  }).join('');
  out += `\t\t'${k}' => '${svg}',\n`;
}
out += "\t);\n}\n\n/**\n * Echo/return an inline icon. $class takes Tailwind classes, $fill sets a fill colour (e.g. 'currentColor').\n */\nfunction skino_icon( $name, $class = 'w-5 h-5', $fill = 'none', $echo = true ) {\n\tstatic $paths = null;\n\tif ( null === $paths ) { $paths = skino_icon_paths(); }\n\tif ( ! isset( $paths[ $name ] ) ) { return ''; }\n\t$svg = sprintf( '<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"%s\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"%s\" aria-hidden=\"true\" data-icon=\"%s\">%s</svg>', esc_attr( $fill ), esc_attr( $class ), esc_attr( $name ), $paths[ $name ] );\n\tif ( $echo ) { echo $svg; // phpcs:ignore WordPress.Security.EscapeOutput\n\t}\n\treturn $svg;\n}\n";
fs.writeFileSync(path.join(root, 'wordpress-theme/skino-theme/inc/icons.php'), out);
console.log('ok');
